TEXT_LOSE         = "GAME OVER";
TEXT_WIN          = "CONGRATULATIONS!!!";
TEXT_SCORE        = "SCORE";
TEXT_PLAY         = "PLAY";
TEXT_RESTART      = "RESTART";
TEXT_EXIT         = "EXIT";
TEXT_GAMEOVER     = "GAME OVER";
TEXT_COMBO        = "COMBO";
TEXT_HELP         = "CUT THE FRUITS\nWITH THE MOUSE\nCURSOR AND AVOID\nTHE BOMBS!";
TEXT_HELP_MOBILE  = "CUT THE FRUITS\nWITH THE FINGER\nAND AVOID THE\nBOMBS!";
        